//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KapustinRPMBDPR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingObject
    {
        public string BuildingObjectName { get; set; }
        public int RegionId { get; set; }
        public int SectorId { get; set; }
        public int OrganizationId { get; set; }
        public int FinanceOfFirstQuart { get; set; }
        public int FinanceOfSecondQuart { get; set; }
        public int FinanceOfThirdQuart { get; set; }
        public int FinanceOfFourthQuart { get; set; }
        public System.DateTime EnterYear { get; set; }    
        public virtual BuildingOrganization BuildingOrganization { get; set; }
        public virtual Region Region { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
